# report result parser

import os, logging
import json
import pandas as pd
from pathlib import Path

__author__ = "Matthias Wess"
__copyright__ = "Christian Doppler Laboratory for Embedded Machine Learning"
__license__ = "Apache 2.0"


def read_report(report="", outfolder="./tmp/"):
    """Reads file in a pandas dataframe and writes layer data into a json file

    Args:
        outfolder: folder where the json data will be stored
        report: filename of the report where the data will be extracted
        format: data format to save the data with - json

    Returns: False if File does not exist 
    """
    if not os.path.exists(report):
        return None

    # Open the text file and read its contents
    with open(report, 'r') as file:
        content = file.read()

    # Split the content into sections based on the headers
    sections = content.split('\n============================== ')

    # Initialize lists to store data
    data = []

    # Loop through each section and extract data
    for section in sections[1:]:
        section_lines = section.strip().split('\n')

        # Extract headers and remove extra whitespace
        headers = [header.strip() for header in section_lines[0].split(', ')]

        # Extract data rows and remove extra whitespace
        rows = [row.strip() for row in section_lines[1:]]

        # Split each row into columns and append to data list
        for row in rows:
            row_data = row.split(', ')
            data.append(row_data)

    # Create a DataFrame
    df = pd.DataFrame(data, columns=headers)

    return df

def r2a(report):
    data = read_report(report)
    print(data)

    if data is False:
        return False

    result = pd.DataFrame(data[['Name','RunTime(ms)']].to_numpy(),columns=['name','time(ms)'])
    print(data)
    print(result)

    return result


def extract_data_from_folder(infold, outfold):
    """Extracts layer name and real time data from a folder of ncs2 reports

    Args:
        infold: folder containing the reports generated by benchmark_app.py
        outfold: folder where the extracted results will be saved

    Returns: none
    """

    # if the output data directory does not exist, create it
    os.makedirs(outfold, exist_ok=True)

    # avg_count holds the csv filenames of the benchmark_average_counters containing layer data
    avg_count = [f for f in os.listdir(infold) if "benchmark_average_counters_report" in f]

    # go over files and extract data
    for i, report in enumerate(avg_count):
        print(i + 1, ": parsing " + os.path.join(infold, report))
        read_report(report=os.path.join(infold, report), outfolder=outfold)


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description='Vela parser')
    parser.add_argument("-if", '--infold', default='./report',
                        help='Folder containing reports', required=True)
    parser.add_argument("-of", '--outfold', default='report_async_extracted',
                        help='folder which will contain the output json files', required=True)
    args = parser.parse_args()
    #read_report(args.infold, args.outfold)
    r2a(args.infold)

